//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignarDataAccessLayer.AzureADBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int AttachmentID { get; set; }
        public int BugID { get; set; }
        public string Name { get; set; }
        public string ContentPath { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Bug Bug { get; set; }
    }
}
